# Generated by Django 5.2.4 on 2025-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_advertisers', models.PositiveIntegerField(default=0)),
                ('total_publishers', models.PositiveIntegerField(default=0)),
                ('total_offers', models.PositiveIntegerField(default=0)),
                ('total_invoices', models.PositiveIntegerField(default=0)),
                ('revenue_today', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_week', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_month', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_revenue_data', models.JSONField(default=list)),
                ('daily_profit_data', models.JSONField(default=list)),
                ('invoice_status_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dashboard Snapshot',
                'verbose_name_plural': 'Dashboard Snapshots',
                'ordering': ['-date'],
            },
        ),
    ]
