# Generated by Django 5.2.4 on 2025-07-26 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_mmp_offer_model_offer_payable_event_and_more'),
        ('publishers', '0003_publisher_name_publisher_teams_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_matches', to='offers.offer')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_matches', to='publishers.wishlist')),
            ],
            options={
                'unique_together': {('offer', 'wishlist')},
            },
        ),
    ]
