# Generated by Django 5.2.4 on 2025-09-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_payout_matchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
        migrations.AddField(
            model_name='offer',
            name='kpi',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
