version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: affiliate_management_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Pkdubey@00
      MYSQL_ROOT_PASSWORD: Pkdubey@00
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    command: gunicorn affiliate_management.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=affiliate_management.settings
      - PYTHONUNBUFFERED=1

volumes:
  db_data:
