# Generated by Django 5.2.4 on 2025-09-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0004_wishlist_created_at_wishlist_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='category',
            new_name='kpi',
        ),
    ]
