# Generated by Django 5.2.4 on 2025-09-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0005_rename_category_wishlist_kpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='model',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='payable_event',
        ),
    ]
