# Generated by Django 5.2.4 on 2025-12-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0006_remove_wishlist_kpi_remove_wishlist_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='name',
        ),
    ]
