# Generated by Django 5.2.4 on 2025-12-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0008_publisher_unique_publisher_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='publisher',
            name='unique_publisher_email',
        ),
    ]
