# Generated by Django 5.2.4 on 2025-07-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0002_delete_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertiser',
            old_name='name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
