# Generated by Django 5.2.4 on 2025-07-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0003_rename_name_advertiser_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='teams_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
