# Generated by Django 5.2.4 on 2025-12-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0004_advertiser_name_advertiser_teams_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='name',
        ),
    ]
