# Generated by Django 5.2.4 on 2025-12-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0005_remove_advertiser_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='advertiser',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_advertiser_email'),
        ),
    ]
