# Generated by Django 5.2.4 on 2025-12-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0006_advertiser_unique_advertiser_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='advertiser',
            name='unique_advertiser_email',
        ),
    ]
