# Generated by Django 5.2.4 on 2026-01-04 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs', '0004_alter_dailyrevenuesheet_options_and_more'),
        ('invoicing', '0014_invoice_validation_alter_invoice_drs'),
        ('publishers', '0009_remove_publisher_unique_publisher_email'),
        ('validation', '0002_validation_approve_payout_validation_conversions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Validation', 'verbose_name_plural': 'Validations'},
        ),
        migrations.AddField(
            model_name='validation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='validation',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_invoices', to='invoicing.invoice'),
        ),
        migrations.AddField(
            model_name='validation',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validation',
            name='drs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='drs.dailyrevenuesheet'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='publishers.publisher'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Invoiced', 'Invoiced'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
