# Generated by Django 5.2.4 on 2025-12-12 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs', '0002_dailyrevenuesheet_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrevenuesheet',
            options={'verbose_name': 'Daily Revenue Sheet', 'verbose_name_plural': 'Daily Revenue Sheets'},
        ),
        migrations.RenameField(
            model_name='dailyrevenuesheet',
            old_name='affiliate',
            new_name='publisher',
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='advertiser_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='conversions_postbacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='geo',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='mmp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='payable_event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='publisher_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyrevenuesheet',
            name='account_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrevenuesheet',
            name='advertiser_conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrevenuesheet',
            name='af_prt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AF/PRT'),
        ),
        migrations.AlterField(
            model_name='dailyrevenuesheet',
            name='campaign_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailyrevenuesheet',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrevenuesheet',
            name='pid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrevenuesheet',
            name='publisher_conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrevenuesheet',
            name='publisher_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
