# Generated by Django 5.2.4 on 2026-01-04 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs', '0003_alter_dailyrevenuesheet_options_and_more'),
        ('invoicing', '0013_alter_invoice_due_date_alter_invoice_invoice_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrevenuesheet',
            options={'ordering': ['-created_at'], 'permissions': [('can_validate_drs', 'Can validate DRS'), ('can_create_invoice', 'Can create invoice from DRS'), ('can_approve_invoice', 'Can approve invoice'), ('can_mark_paid', 'Can mark invoice as paid')], 'verbose_name': 'Daily Revenue Sheet', 'verbose_name_plural': 'Daily Revenue Sheets'},
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drs_invoices', to='invoicing.invoice'),
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_drs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_drs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyrevenuesheet',
            name='validation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailyrevenuesheet',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('validated', 'Validated'), ('invoiced', 'Invoiced'), ('approved', 'Approved'), ('paid', 'Paid')], default='active', max_length=20),
        ),
    ]
