# Generated by Django 5.2.4 on 2026-01-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs', '0004_alter_dailyrevenuesheet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrevenuesheet',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('paid', 'Paid')], default='active', max_length=20),
        ),
    ]
