# Generated by Django 5.2.4 on 2025-09-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0004_advertiser_name_advertiser_teams_id_and_more'),
        ('publishers', '0004_wishlist_created_at_wishlist_updated_at'),
        ('users', '0003_user_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='publisher',
        ),
        migrations.AddField(
            model_name='user',
            name='advertisers',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='advertisers.advertiser'),
        ),
        migrations.AddField(
            model_name='user',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='publishers.publisher'),
        ),
    ]
