# Generated by Django 5.2.4 on 2025-07-15 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drs', '0001_initial'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drs.dailyrevenuesheet')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.publisher')),
            ],
        ),
    ]
