# Generated by Django 5.2.4 on 2025-07-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('INR', 'INR')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/pdf/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='publisher_upload',
            field=models.FileField(blank=True, null=True, upload_to='invoices/uploads/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Overdue', 'Overdue')], max_length=20),
        ),
    ]
