# Generated by Django 5.2.4 on 2025-07-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_invoice_amount_invoice_currency_invoice_gst_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('rate_to_inr', models.DecimalField(decimal_places=6, max_digits=12)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
