# Generated by Django 5.2.4 on 2025-08-06 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0004_advertiser_name_advertiser_teams_id_and_more'),
        ('invoicing', '0003_currencyrate'),
        ('publishers', '0004_wishlist_created_at_wishlist_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='publisher_upload',
        ),
        migrations.AddField(
            model_name='invoice',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisers.advertiser'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='party_type',
            field=models.CharField(choices=[('publisher', 'Publisher'), ('advertiser', 'Advertiser')], default='publisher', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publishers.publisher'),
        ),
    ]
