# Generated by Django 5.2.4 on 2025-08-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_remove_invoice_publisher_upload_invoice_advertiser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default='2025-08-27'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default='2025-08-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='INV-0001', max_length=100),
        ),
    ]
