# Generated by Django 5.2.4 on 2025-10-03 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs', '0002_dailyrevenuesheet_updated_at_and_more'),
        ('invoicing', '0006_invoice_bank_details_invoice_bill_from_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='drs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drs.dailyrevenuesheet'),
        ),
    ]
