# Generated by Django 5.2.4 on 2025-10-08 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_alter_invoice_drs'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_account_name',
            field=models.CharField(blank=True, default='traccify.ai', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_account_number',
            field=models.CharField(blank=True, default='50200094727751', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_branch_address',
            field=models.TextField(blank=True, default='Ward No 12, Gr Flr, Muslim Chowdhirian, Dhampur, Hayatnagar Seohara Bijnor - 246746'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, default='HDFC0007070', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(blank=True, default='HDFC Bank', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_swift_code',
            field=models.CharField(blank=True, default='HDFCINBB', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_from_address_line1',
            field=models.TextField(blank=True, default='Trademark Sechura Thakurdwara Road, Bazar'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_from_address_line2',
            field=models.TextField(blank=True, default='Krishn, Bijnor, Uttar Pradesh, India, 246746'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_from_company',
            field=models.CharField(blank=True, default='WGROUP', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_from_email',
            field=models.EmailField(blank=True, default='finance@traccify.ai', max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_from_gstin',
            field=models.CharField(blank=True, default='09AMFPV3992D1ZL', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_from_msme_new',
            field=models.CharField(blank=True, default='MSME: UP/YAM-UP-17-0028662', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_from_registration_new',
            field=models.CharField(blank=True, default='Company Registration No: 09AMFPV3992D1ZL', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_address_new',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_company_new',
            field=models.CharField(blank=True, default='Rohan Technology', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_email_new',
            field=models.EmailField(blank=True, default='rohan@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_gstin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='net_terms',
            field=models.CharField(blank=True, default='Net 30', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_days',
            field=models.CharField(blank=True, default='30', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Overdue', 'Overdue')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(default='Service', max_length=200)),
                ('hsn_sac', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.IntegerField(default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
