# Generated by Django 5.2.4 on 2025-10-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_create_invoiceline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
