# Generated by Django 5.2.4 on 2025-10-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_alter_invoiceline_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bill_from_company',
            field=models.CharField(blank=True, default='Traccify', max_length=200),
        ),
    ]
