# Generated by Django 5.2.4 on 2025-10-17 06:40

import apps.invoicing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_alter_invoice_amount_alter_invoice_cgst_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, default=apps.invoicing.models.default_due_date, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
