# Generated by Django 5.2.4 on 2026-01-04 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drs', '0004_alter_dailyrevenuesheet_options_and_more'),
        ('invoicing', '0013_alter_invoice_due_date_alter_invoice_invoice_number'),
        ('validation', '0002_validation_approve_payout_validation_conversions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_invoices', to='validation.validation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='drs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_drs', to='drs.dailyrevenuesheet'),
        ),
    ]
